import os
from dotenv import load_dotenv
from groq import Groq

load_dotenv()
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def get_llm_signal(text: str) -> float:
    """
    Sends text to Groq's LLM and asks it to assess AI vs human likelihood.
    Returns a float between 0 and 1, where higher = more likely AI-generated.
    """
    prompt = f"""You are an AI content detector. Analyze the following text and 
assess the likelihood it was generated by an AI rather than written by a human.

Respond with ONLY a single number between 0 and 1, where:
- 0.0 means you are certain it is human-written
- 1.0 means you are certain it is AI-generated
- 0.5 means you are completely uncertain

Do not include any explanation, words, or punctuation — only the number.

Text to analyze:
\"\"\"{text}\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.0,
    )

    raw_output = response.choices[0].message.content.strip()

    try:
        score = float(raw_output)
        # clamp between 0 and 1 in case the model returns something out of range
        score = max(0.0, min(1.0, score))
    except ValueError:
        # fallback if the model returns something unparseable
        score = 0.5

    return score


# Standalone test block — only runs when you execute this file directly
if __name__ == "__main__":
    test_texts = [
        "Artificial intelligence represents a transformative paradigm shift in modern society. It is important to note that while the benefits of AI are numerous, it is equally essential to consider the ethical implications.",
        "ok so i finally tried that new ramen place downtown and honestly? underwhelming. the broth was fine but they put WAY too much sodium in it.",
    ]

    for t in test_texts:
        score = get_llm_signal(t)
        print(f"Score: {score}  |  Text: {t[:60]}...")